// <auto-generated />
using System;
using BancoTalentos.CandidatoService.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BancoTalentos.CandidatoService.Migrations
{
    [DbContext(typeof(ContatoContext))]
    partial class ContatoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BancoTalentos.CandidatoService.Model.Cidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EstadoId");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.ToTable("Cidade");
                });

            modelBuilder.Entity("BancoTalentos.CandidatoService.Model.Contato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CidadeId");

                    b.Property<DateTime>("DataCriacao");

                    b.Property<string>("Email");

                    b.Property<string>("Nome");

                    b.Property<string>("Skype");

                    b.Property<string>("Telefone");

                    b.Property<string>("UltimoNome");

                    b.HasKey("Id");

                    b.HasIndex("CidadeId")
                        .IsUnique()
                        .HasFilter("[CidadeId] IS NOT NULL");

                    b.ToTable("Contato");
                });

            modelBuilder.Entity("BancoTalentos.CandidatoService.Model.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Estado");
                });

            modelBuilder.Entity("BancoTalentos.CandidatoService.Model.Cidade", b =>
                {
                    b.HasOne("BancoTalentos.CandidatoService.Model.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId");
                });

            modelBuilder.Entity("BancoTalentos.CandidatoService.Model.Contato", b =>
                {
                    b.HasOne("BancoTalentos.CandidatoService.Model.Cidade", "Cidade")
                        .WithOne("Contato")
                        .HasForeignKey("BancoTalentos.CandidatoService.Model.Contato", "CidadeId");
                });
#pragma warning restore 612, 618
        }
    }
}
